image: python:3.6

pages:
  script:
  - pip install lektor
  - lektor plugins add lektor-conference-template-functions
  - lektor build --output-path public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

#stages:
#- test
#sast:
#  stage: test
#include:
#- template: Security/SAST.gitlab-ci.yml

